[features]
seeds = false
skip-lint = false

[provider]
cluster = "devnet"
wallet = "~/.config/solana/idlebot-wallet.json"

[programs.localnet]
idlebot-anchor-workspace = "j9194JViAkUpfSgZc3CMxGSS8ANCCAHqZAJvfhJzdaZ"

[programs.devnet]
idlebot-anchor-workspace = "j9194JViAkUpfSgZc3CMxGSS8ANCCAHqZAJvfhJzdaZ"

[registry]
url = "https://api.apr.dev"